apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:JbKrUCh7s5sGLlAqvttdj9wUEiW1n/RG,iv:Y/ApGaUNhErYnkLLCRw8cOjUJiwkEYlAD9cHh3oerRk=,tag:KFDqss1aCJkJ7GeV0RcwPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sxj35hpuyzh8zpgsxs3tg40wdm79vttlra35q88sdefdsqh3pgfqfppfjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSmFDOE5aOEF0TTN1N1hi
            aVVPSmgzcXlLQmFtcGl6T1hUb3pWSHFNcXpRClBOVHVXM29hcU1nT1N0UUpxYm1x
            QmtsVUlTaitqRFJXMFZZcjY5ejBOdmcKLS0tIDlmeTZSM205b3BOc0lmYUxBMzV6
            Z1RFSHdIOThYc3dTWCtpanJ6RGZudTAK+FNydappGFNRi2Nyb2cNPnIAyM0luWBm
            OKpn2qRhmF3mnEmQi1TUl3eZUoHxnIEogAGXCgykMPN65EAAtYOxvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-18T12:39:10Z"
    mac: ENC[AES256_GCM,data:eMiJBvwo5/kG+JLbj7aww+xmr8c/KQcE8xi/f0k/zk/+pQ8iDad/qjr99ginNujPpm5AkMZqcZRU1HZ2c2luUIG+yr9beIXaS8EZfMFZZBw3HHAKzbqdxS0c2f5qE+IiBQiXRH+BL2ycJV7YSPKn2pP2JaHlsfc7TIZMjFTFw1w=,iv:1brECFb466GEdtGIx5zqN/2dKFikk0sl87E1HHubauA=,tag:CzjQwhq8YX2SDu3YMkmvpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
