---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  values:
    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.15.0
        env:
          TZ: ${TIMEZONE}
        workingDir: /config
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            hajimari.io/appName: "Hass Config"
            hajimari.io/icon: cib:visual-studio-code
            hajimari.io/group: home
          hosts:
            - host: "hass-code.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - *host
        volumeMounts:
          - name: config
            mountPath: /config
        resources:
          requests:
            cpu: 10m
            memory: 180M
          limits:
            memory: 300M
