---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: POSTGRES_SUPER_USER
      remoteRef:
        key: authentik
        property: POSTGRES_SUPER_USER
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: authentik
        property: POSTGRES_SUPER_PASS
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: authentik
        property: AWS_ACCESS_KEY_ID
    - secretKey: AUTHENTIK_KEY
      remoteRef:
        key: authentik
        property: AUTHENTIK_KEY
    - secretKey: SECRET_EMAIL
      remoteRef:
        key: authentik
        property: SECRET_EMAIL
