---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name authentik-secret
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      data:
        values.yaml: |
          postgresql:
            postgresqlPassword: "{{ .postgres_password }}"
          authentik:
            postgresql:
              password: "{{ .postgres_password }}"
            email:
              username: "{{ .email_username }}"
              password: "{{ .email_password }}"
            secret_key: "{{ .secret_key }}"
            redis:
              password: "{{ .redis_password }}"
  dataFrom:
    - extract:
        key: authentik
