---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: security
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        values.yaml: |-
          postgresql:
            postgresqlPassword: "{{ .postgres_password }}"
          # redis:
          #   redisPassword: "{{ .redis_password }}"
          authentik:
            postgresql:
              password: "{{ .postgres_password }}"
            # redis:
            #   password: "{{ .redis_password }}"
            email:
              username: "{{ .email_username }}"
              password: "{{ .email_password }}"
            secret_key: "{{ .secret_key }}"
  data:
    - secretKey: postgres_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 3ff34fd7-ec65-436c-865c-afcf0104ce37
        property: postgresql_password
    # - secretKey: redis_password
    #   sourceRef:
    #     storeRef:
    #       name: bitwarden-fields
    #       kind: ClusterSecretStore
    #   remoteRef:
    #     key: 3ff34fd7-ec65-436c-865c-afcf0104ce37
    #     property: redis_password
    - secretKey: email_username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: e09429a9-e6ef-49a1-bd0a-afc50145dc9c
        property: username
    - secretKey: email_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: e09429a9-e6ef-49a1-bd0a-afc50145dc9c
        property: password
    - secretKey: secret_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 3ff34fd7-ec65-436c-865c-afcf0104ce37
        property: key
