apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:r2UM1ScF0GaUvIbhbtHqe5ZB8Y0rcy2GRjb1pA8yxddfhTkqxk7oJu/XtLZcph0ebkIp0gyE2CmEWd0l,iv:T/d4vsZDxq3lAP9DnHwEzqwwsLqDBN8UVufumQzpvMg=,tag:FbamkL/6ao4Uy71nhEPy5A==,type:str]
    username: ENC[AES256_GCM,data:1qQGmeM=,iv:szWr9tDKTsoaWinTDXtLTZwx4Mq/fWvhWi74mV/INKE=,tag:6mmfp3zHNKUoD/HRsLXxqw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sxj35hpuyzh8zpgsxs3tg40wdm79vttlra35q88sdefdsqh3pgfqfppfjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcXJrOTVCTllTSCtTenB6
            MDQ0QktmRU9sZnM1QXRFWXR1R2lPWXBURFNvCjlwZkw3SXpFWStGbjRrTVk2TlZl
            d08vZFdWS2tPNGZ3MmtlSEo4R1lqTDgKLS0tIGRSZVlDUU8xSnJ5UmV3YXZZS1lG
            eXA5QmFsY2pib0lqYmlnUXI4c3pIRU0KaQ2co3TG+vMSBEiRSaTNy7LNpL0NIGDF
            LSvB74aLjFWzMwe3+lddOJTgB2e4PWY7xEwduR3G9y0ggRm/Z7DHaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-18T11:46:10Z"
    mac: ENC[AES256_GCM,data:6FtKca5zcedfr1SYtmDw0PLVqCzdg3qPtvxuQARAbix+iTx9USxPhBhWmimEYpq3RfxLFfpUpVXoLlSiGKEV/fCrmQZ8L62aGt6O9RuAEGuOylRZnWb3Xu19t4uG2V0a3nz+yTc1Tvjli1C1uocuP5fwvBX7FOMCdVF5RCstB00=,iv:NcpoiRnACc8tt/IWAm+vxBmzqndb8NKy27LQgAxNLSQ=,tag:nw+ddhsYjF6BB3qCFuXQtw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
