apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:9qz7jCz4PFvl9dGfTmEZL1pG//AIaWk7KQ==,iv:Q2XHMf2RPASa9fC3QKzu2RECDY4xkI6mJ2D5s26L504=,tag:oYH/8q4katKe8m9I+urQuA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:CA/lnCikF2vX4vC2KxN/MjO4OoNEVwhFhAmi7Y6g5AJg5+MJ,iv:F9Igo/a4pqUY/tUvOJwKv/XExO7607mvasy3Ys0TInI=,tag:2BSJQiufQOuyjsEz6lRUCA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:IpMODV/w7bUdAJw=,iv:23rGLT1rbVCWJI231DbceqvgFGdGASVIjTrCx4Q7cV8=,tag:sQwPTp+q6FZUnz7B9Uw23g==,type:str]
    blog_name: ENC[AES256_GCM,data:l1fuQ1L7DT0=,iv:3bndpKGghqyfaRvn0QQKbhACE1v0Vpok/3Y5iycJCko=,tag:iYdLl5E1td8Tcey/B+e6jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sxj35hpuyzh8zpgsxs3tg40wdm79vttlra35q88sdefdsqh3pgfqfppfjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRFp6ZlhxRE1pTlRtS3Fa
            cFE4TVRoTVAzT1FVSUo2c1dqR1ZuSTJieWxvCkw3V0x1Z01uNVc2Vlg1NWNIOTJB
            ZHdNeGtBdlBROXFMc0JJR1l2WFA4YTQKLS0tIHVtZ0ZFZVIvQkxUM1JkcnlVam04
            d0ZDRmQydHc4cDkzKy8wcmdYNmxKZTQKXB1E73GOP9yBdMVH5xOYuESyXKTUCqey
            3de0NQXyvfjHO7NZZPHKyllHyQ8JsSpuVh+AS+FXZ3o8M3ImZs4uYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-26T15:25:14Z"
    mac: ENC[AES256_GCM,data:q0uvFNvomppjQDNAMVW2aW+SnsYrr7F2+FVxNZQbmLv/vqPIxuvidXE/Py4DEr2aq3IKhtmqCylsN9joVgA+8RvjNUVPDXHxBYQe5B2QLVGQYH3xTrVVdsy5bZheF6lCV8aLP6sHcrkAanQSyCbCxJyV88CskpTAc5YQHDdhZJU=,iv:ctXxfTMvlP8UmHI/f/Dkgq/F5khTFX6cyrjSMdjlr7Q=,tag:K7g59SLDSQmsR/XVfw0NPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
