---
apiVersion: v1
kind: Service
metadata:
  name: postgres-ext
  namespace: database
  annotations:
    coredns.io/hostname: pg.${SECRET_DOMAIN}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: "192.168.3.230"
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    application: spilo
    cluster-name: postgres
    spilo-role: master
