---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.jsonapiVersion: external-secrets.io/v1beta1
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
  namespace: kube-system
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect:8080
      vaults:
        Kubernetes: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-secret
            key: token
            namespace: kube-system
