apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:BOwUhZHm3gDXFGqrxqZKXa+ThBc6Ij6/nn2HQXvwbdNT+HmE,iv:+v/oLGxfGR7iUaa51NGEVJM/vUiPx3ifUdZn5STGLFQ=,tag:ZoOpgeG3/YzBrD/k1+GbcA==,type:str]
    credentials.json: ENC[AES256_GCM,data:H7dKlevy6pTWDcUGnX2OXZn+Cl7PTe5NeW/2qWhNVPbNsGxNSVfEEZ89vM9ePdQZp+qqt1AFfDOLiv4jgDTY+ZaLZ2tgrGJ7ICJ0LN+Z7+kFqLVB17ARMomn8wR0CecnLm9XcEL0pdgk8Z8cB5vyKHHZ+BBhyfdK2sjv5vUYA/bI1gSVnYuSk9QN03sFek2oHM+QZccy4SxqTfAZyO0PtgvqaAJqj5WkXMvz/0cLZQ==,iv:rVV9+JoKd91XP7SxvRMpaCHI6mU3zfpQfI9UKydptkA=,tag:eHC9MX8iZ6o2pPYIwIrNMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sxj35hpuyzh8zpgsxs3tg40wdm79vttlra35q88sdefdsqh3pgfqfppfjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWjFDWWtoMW1HZ0I5MXVT
            QndNcGU5dS8xeGVsMHJWRmh2ZXdUa0ZsakRRCkNBczB1QlU4TUZNSVVnRklZOUxZ
            Mm5tdWg3RVBLUzh4WGtEY2dLYVlSRTgKLS0tIGNRUjdzRGVKZXV1RkRyQU9YOXI0
            T1lUcXlDSW82ZEpsV1BoS0JCN1Z4WlUKfSzUVUtzuPnTRgsbGrzAwUmlpxkyxOfj
            s/L3VvKAoAaVaKEnOP/ZrkesHQayw0LwwuyHbXBzr8f67EGOQSlu1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-21T10:25:27Z"
    mac: ENC[AES256_GCM,data:tuugF2X64AppxGTJnLxW320HXJqvqdK42ayKjf4LoPrs7N2pxUbZcLrYT0T3fUuGbTCfzWeOX4kb8dI/1Nic0S8MTfyr16soY4nlDo2PQX5yZJwt0oJUnxrdKOEaABpCsNcalgjL0+UzkVoPl5m+ZFP41rlUDatdykL2ZiaEs9M=,iv:6jhIS7BdHw3tCtCtnj0F99jGe5xM0LiyWlofONPSgAM=,tag:mamjBnliLNi99/wDRRySrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
