apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:b0lEJz88UMvPgaDbYKxvqDCXM0ioXL1HTpx1p/eCvh/HCcXL,iv:3Uz3UoOgiLS6KGy25N1eFCtqzp+aWzfg5We9UllX1lE=,tag:5EcRXGQVbvC1X7uPiL2nTQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:S24aifhFbqbQO2ZKBXuyHaT+Q5LhHt8fjZmpcGesQZ6PCZBXHfaEKvTeCXvf5E6zoHRjm+BRnLvZDBweQKu9R47IBoxbqiFTQ8ITDVn7lMyi0fuJVIVDiaQheqyOTxR0Yym12RjPynt+eEynFW9ZmvA+2PGbdgafwJpnyhEaZhL570Y4+16+lWqwBhzTm3oKxjtyD8kD1PQptr88wg2pTA+7RtyjaEVqYNrf+vboTQ==,iv:bTUkTGnlQasrzgCEhmunyJqbI0uqyC2FtCBptrKkLms=,tag:zt9bPU2v+xM0PBTnuVDt8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sxj35hpuyzh8zpgsxs3tg40wdm79vttlra35q88sdefdsqh3pgfqfppfjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTGltYm9Xbm5NQWRMUnhQ
            SjFmRlZrRE1PQXF6ZVdLOS9XamZ1dDdTV0VrCjQ1WTFQV04vQ2t2aUxDQUt6dm1v
            TVRtODNoRW03UWN6aEl3Y1RRREliclEKLS0tIGZiUXE4UmkyWWtIMDVzVktBdDN5
            Z2poeWVtd2o2czd4Rll3ZHVnUE1rSEkK+Exad+TNHrU0BYoOcsGudpXLJ4jJ07I7
            XrqzRKOAda1K34dH2Rsb5pGKiR8vSJovQkCeIMSgr428Wj1Ng+ueJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-18T12:39:10Z"
    mac: ENC[AES256_GCM,data:vPNPQ5cQm8Z2mYB2VcZsVVi1Uk0wNjkZ17kDwl8TcdHQ1yxmBXf8SE7bxTDhI/M31/7OhB8sQfDo4juKcIdvgMW93gpMWrY/jZ742Cc1EJEOrKDOduosQiqZSpsUEzk8Bls6b40Z8Ko7niaiZ87TPu5yms5O6nLfq6Mp+bCSd+k=,iv:UV3bnXQMy/l4FvWWqdXHpiH5bsDIBqJxBY90JMi2fx0=,tag:OEfg+OLTKEXlGutIen1FTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
