apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:VD7pIbi4vA8huZ8LHJGP7sFYl06HV5feSyrpV8l+UuhLZwIs,iv:jh4+DCTzx56xLQdmCNvRJwf37FWCkZx7EnRdXfdRoQM=,tag:9xU9rRwLg4CQyOhokZX+oQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:4Hlcb89zCL+1XqmKq2hAdsih/p6fxTRORZIPSynZ+cZAAB8F8YOYze/dox5bUjylPvnMuCP1LXEhpOT8rLdgwhvXzkbO2r6OPp0bHvPJQa6NhWGgn9ZxO15snCG/LavL2HMJR9b5/5LbX+5vwZpYdsvQtlN/tPSBmd0q0GgThrgFZbfmL083fQpkguP6mau5FtZBN9MqAHjPdR1q7Wlzmosi2fh1FhgZqJpiTG2dGQ==,iv:4ycLuoxa0DkBrs072C2vmATG3VXjGnm4k9TEHs40Dm0=,tag:dmxDXncZLo+oMmyKBQx0VQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sxj35hpuyzh8zpgsxs3tg40wdm79vttlra35q88sdefdsqh3pgfqfppfjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrY3pGQmlOcElmVVUzakpa
            cWtCTHZFcjFIYmdqSFJpWUN1dFM1d2pnc1RRCnRYcm9oK1lpMys3Rmg0WjM4Qk1N
            SnluQVlIaXpVT1hxQjdsYTJxSVBRRWMKLS0tIGxiWkpaQ0FJQmNiMmVITW5icHJP
            ZVN4RVFPdm9Zd0VwaFNwWjRzZDRvamsKUfwpUGKfr6W3+RRc9RHtgEzm5uU5jx61
            y5tk7LmnTDtdvg82MSc/22w0cOQ17QNjpEKiL65WYP7bl4AFLoC2Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-18T11:46:05Z"
    mac: ENC[AES256_GCM,data:dTyVJyi1bnYAtOIzWj7NW0phbFAdz1SSa5LlWiT/oetz7toVpnuU6tI/+jxtlePsj2uyl90XjslNeq2gBFTmkzc35V+IMXat7f2LzPnPSSd4sHMgpMKTyKnCFElp2UIk6YZrFCAeX6OwzXIAUJqquRpChuRh8ti8tb2OoF0cLJk=,iv:w+EtjfGrBGd98sCHG3t//Qk4rryrjrAkiEGCghtCHV4=,tag:VOqKlDps/n0dC9zqd1eMbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
