---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2023.7.2
    env:
      TZ: "Europe/Berlin"
 #     SECRET_RECORDER_DB_URL:
 #       valueFrom:
 #         secretKeyRef:
 #           name: database-home-assistant-user
  #          key: POSTGRES_URL
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    service:
      main:
        ports:
          http:
            port: 8123
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.${SECRET_DOMAIN}
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Home Assistant"
          gethomepage.dev/group: "Collaboration"
          gethomepage.dev/icon: "home-assistant"
        hosts:
          - host: &host hass.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    persistence:
      dbus: # needed for Bluetooth
        enabled: true
        type: hostPath
        hostPath: &dbus /run/dbus
        mountPath: *dbus
      config:
        enabled: true
        storageClass: longhorn
        existingClaim: home-assistant-config
        mountPath: /config
        retain: true
    resources:
      requests:
        cpu: 10m
        memory: 1250Mi
      limits:
        memory: 1250Mi
    nodeSelector:
      bluetooth: "true"
